# Generated by Django 2.2 on 2019-06-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('year', 'title')},
        ),
    ]
