# Generated by Django 2.2 on 2019-07-29 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Profile',
        ),
    ]
